version: '3'

services:
  api:
    build: ./app
    container_name: fastapi
    volumes: 
      - image-volume:/code/app/images
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - mongo-app
  mongo:
    image: mongo:4.4.6
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-app
  client-react:
    build: ./react-app
    container_name: react-container
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - mongo-app

networks:
    mongo-app:
        driver: bridge

volumes:
    data-volume:
    image-volume:
